[build]
builder = "nixpacks"
buildCommand = "cd bskyweb && go build -v -tags timetzdata -o bskyweb ./cmd/bskyweb"

[deploy]
startCommand = "cd bskyweb && ./bskyweb serve --http-address=0.0.0.0:$PORT --appview-host=https://public.api.bsky.app"
restartPolicyType = "ON_FAILURE"